---
- name: setup services
  hosts: all
 # become: true
  tasks:
    - name: start and enable httpd and firewalld
      ansible.builtin.service:
        name: "{{ itemmmm }}"
        state: started
        enabled: true
      loop:
        - httpd
        - firewalld
